<?php
$classes = ' festi-cart-horizontal-position-'.$settings['windowCartHorizontalPosition'];

$classes .= ' festi-cart-vertical-position-'.$settings['windowCartVerticalPosition'];

if (isset($settings['windowCartFixedPosition'])) {
    $classes .= ' festi-cart-fixed-position';
}
?>
<div
     
    class="festi-cart-window-content <?php echo $classes; ?>"
>
    <a class="festi-cart festi-cart-window"></a>
</div>